#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.LinqToSql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GLXNAVWebApp_TEST")]
	public partial class POWaitingForApproveDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPOWaitingForApprove(POWaitingForApprove instance);
    partial void UpdatePOWaitingForApprove(POWaitingForApprove instance);
    partial void DeletePOWaitingForApprove(POWaitingForApprove instance);
    #endregion
		
		public POWaitingForApproveDataContext() : 
				base(global::DAL.Properties.Settings.Default.GLXNAVWebAppConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public POWaitingForApproveDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public POWaitingForApproveDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public POWaitingForApproveDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public POWaitingForApproveDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<POWaitingForApprove> POWaitingForApproves
		{
			get
			{
				return this.GetTable<POWaitingForApprove>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.POWaitingForApprove")]
	public partial class POWaitingForApprove : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _UID;
		
		private string _Batch;
		
		private string _No;
		
		private string _Type;
		
		private string _Action_Message;
		
		private System.Nullable<bool> _Accept_Action_Message;
		
		private string _Description;
		
		private string _Remark;
		
		private string _Location_Code;
		
		private System.Nullable<decimal> _Original_Quantity;
		
		private System.Nullable<decimal> _Quantity;
		
		private string _Unit_of_Measure_Code;
		
		private System.Nullable<decimal> _Direct_Unit_Cost;
		
		private System.Nullable<System.DateTime> _Due_Date;
		
		private string _Vendor_No;
		
		private string _Vendor_Item_No;
		
		private string _Replenishment_System;
		
		private string _Status;
		
		private string _Comment;
		
		private string _ConvertType;
		
		private System.Nullable<bool> _Converted;
		
		private string _CreatedBy;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private string _UpdatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private string _ApprovedBy;
		
		private System.Nullable<System.DateTime> _ApprovedOn;
		
		private string _ChangeLog;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUIDChanging(System.Guid value);
    partial void OnUIDChanged();
    partial void OnBatchChanging(string value);
    partial void OnBatchChanged();
    partial void OnNoChanging(string value);
    partial void OnNoChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnAction_MessageChanging(string value);
    partial void OnAction_MessageChanged();
    partial void OnAccept_Action_MessageChanging(System.Nullable<bool> value);
    partial void OnAccept_Action_MessageChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnLocation_CodeChanging(string value);
    partial void OnLocation_CodeChanged();
    partial void OnOriginal_QuantityChanging(System.Nullable<decimal> value);
    partial void OnOriginal_QuantityChanged();
    partial void OnQuantityChanging(System.Nullable<decimal> value);
    partial void OnQuantityChanged();
    partial void OnUnit_of_Measure_CodeChanging(string value);
    partial void OnUnit_of_Measure_CodeChanged();
    partial void OnDirect_Unit_CostChanging(System.Nullable<decimal> value);
    partial void OnDirect_Unit_CostChanged();
    partial void OnDue_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnDue_DateChanged();
    partial void OnVendor_NoChanging(string value);
    partial void OnVendor_NoChanged();
    partial void OnVendor_Item_NoChanging(string value);
    partial void OnVendor_Item_NoChanged();
    partial void OnReplenishment_SystemChanging(string value);
    partial void OnReplenishment_SystemChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnConvertTypeChanging(string value);
    partial void OnConvertTypeChanged();
    partial void OnConvertedChanging(System.Nullable<bool> value);
    partial void OnConvertedChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    partial void OnUpdatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedOnChanged();
    partial void OnApprovedByChanging(string value);
    partial void OnApprovedByChanged();
    partial void OnApprovedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnApprovedOnChanged();
    partial void OnChangeLogChanging(string value);
    partial void OnChangeLogChanged();
    #endregion
		
		public POWaitingForApprove()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UID
		{
			get
			{
				return this._UID;
			}
			set
			{
				if ((this._UID != value))
				{
					this.OnUIDChanging(value);
					this.SendPropertyChanging();
					this._UID = value;
					this.SendPropertyChanged("UID");
					this.OnUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Batch", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Batch
		{
			get
			{
				return this._Batch;
			}
			set
			{
				if ((this._Batch != value))
				{
					this.OnBatchChanging(value);
					this.SendPropertyChanging();
					this._Batch = value;
					this.SendPropertyChanged("Batch");
					this.OnBatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="NVarChar(50)")]
		public string No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this.OnNoChanging(value);
					this.SendPropertyChanging();
					this._No = value;
					this.SendPropertyChanged("No");
					this.OnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Action_Message", DbType="NVarChar(50)")]
		public string Action_Message
		{
			get
			{
				return this._Action_Message;
			}
			set
			{
				if ((this._Action_Message != value))
				{
					this.OnAction_MessageChanging(value);
					this.SendPropertyChanging();
					this._Action_Message = value;
					this.SendPropertyChanged("Action_Message");
					this.OnAction_MessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accept_Action_Message", DbType="Bit")]
		public System.Nullable<bool> Accept_Action_Message
		{
			get
			{
				return this._Accept_Action_Message;
			}
			set
			{
				if ((this._Accept_Action_Message != value))
				{
					this.OnAccept_Action_MessageChanging(value);
					this.SendPropertyChanging();
					this._Accept_Action_Message = value;
					this.SendPropertyChanged("Accept_Action_Message");
					this.OnAccept_Action_MessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(50)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location_Code", DbType="NVarChar(50)")]
		public string Location_Code
		{
			get
			{
				return this._Location_Code;
			}
			set
			{
				if ((this._Location_Code != value))
				{
					this.OnLocation_CodeChanging(value);
					this.SendPropertyChanging();
					this._Location_Code = value;
					this.SendPropertyChanged("Location_Code");
					this.OnLocation_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Original_Quantity", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Original_Quantity
		{
			get
			{
				return this._Original_Quantity;
			}
			set
			{
				if ((this._Original_Quantity != value))
				{
					this.OnOriginal_QuantityChanging(value);
					this.SendPropertyChanging();
					this._Original_Quantity = value;
					this.SendPropertyChanged("Original_Quantity");
					this.OnOriginal_QuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_of_Measure_Code", DbType="NVarChar(50)")]
		public string Unit_of_Measure_Code
		{
			get
			{
				return this._Unit_of_Measure_Code;
			}
			set
			{
				if ((this._Unit_of_Measure_Code != value))
				{
					this.OnUnit_of_Measure_CodeChanging(value);
					this.SendPropertyChanging();
					this._Unit_of_Measure_Code = value;
					this.SendPropertyChanged("Unit_of_Measure_Code");
					this.OnUnit_of_Measure_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direct_Unit_Cost", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Direct_Unit_Cost
		{
			get
			{
				return this._Direct_Unit_Cost;
			}
			set
			{
				if ((this._Direct_Unit_Cost != value))
				{
					this.OnDirect_Unit_CostChanging(value);
					this.SendPropertyChanging();
					this._Direct_Unit_Cost = value;
					this.SendPropertyChanged("Direct_Unit_Cost");
					this.OnDirect_Unit_CostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Due_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Due_Date
		{
			get
			{
				return this._Due_Date;
			}
			set
			{
				if ((this._Due_Date != value))
				{
					this.OnDue_DateChanging(value);
					this.SendPropertyChanging();
					this._Due_Date = value;
					this.SendPropertyChanged("Due_Date");
					this.OnDue_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vendor_No", DbType="NVarChar(50)")]
		public string Vendor_No
		{
			get
			{
				return this._Vendor_No;
			}
			set
			{
				if ((this._Vendor_No != value))
				{
					this.OnVendor_NoChanging(value);
					this.SendPropertyChanging();
					this._Vendor_No = value;
					this.SendPropertyChanged("Vendor_No");
					this.OnVendor_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vendor_Item_No", DbType="NVarChar(50)")]
		public string Vendor_Item_No
		{
			get
			{
				return this._Vendor_Item_No;
			}
			set
			{
				if ((this._Vendor_Item_No != value))
				{
					this.OnVendor_Item_NoChanging(value);
					this.SendPropertyChanging();
					this._Vendor_Item_No = value;
					this.SendPropertyChanged("Vendor_Item_No");
					this.OnVendor_Item_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Replenishment_System", DbType="NVarChar(50)")]
		public string Replenishment_System
		{
			get
			{
				return this._Replenishment_System;
			}
			set
			{
				if ((this._Replenishment_System != value))
				{
					this.OnReplenishment_SystemChanging(value);
					this.SendPropertyChanging();
					this._Replenishment_System = value;
					this.SendPropertyChanged("Replenishment_System");
					this.OnReplenishment_SystemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConvertType", DbType="NVarChar(50)")]
		public string ConvertType
		{
			get
			{
				return this._ConvertType;
			}
			set
			{
				if ((this._ConvertType != value))
				{
					this.OnConvertTypeChanging(value);
					this.SendPropertyChanging();
					this._ConvertType = value;
					this.SendPropertyChanged("ConvertType");
					this.OnConvertTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Converted", DbType="Bit")]
		public System.Nullable<bool> Converted
		{
			get
			{
				return this._Converted;
			}
			set
			{
				if ((this._Converted != value))
				{
					this.OnConvertedChanging(value);
					this.SendPropertyChanging();
					this._Converted = value;
					this.SendPropertyChanged("Converted");
					this.OnConvertedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(50)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="NVarChar(50)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovedBy", DbType="NVarChar(50)")]
		public string ApprovedBy
		{
			get
			{
				return this._ApprovedBy;
			}
			set
			{
				if ((this._ApprovedBy != value))
				{
					this.OnApprovedByChanging(value);
					this.SendPropertyChanging();
					this._ApprovedBy = value;
					this.SendPropertyChanged("ApprovedBy");
					this.OnApprovedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ApprovedOn
		{
			get
			{
				return this._ApprovedOn;
			}
			set
			{
				if ((this._ApprovedOn != value))
				{
					this.OnApprovedOnChanging(value);
					this.SendPropertyChanging();
					this._ApprovedOn = value;
					this.SendPropertyChanged("ApprovedOn");
					this.OnApprovedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeLog", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ChangeLog
		{
			get
			{
				return this._ChangeLog;
			}
			set
			{
				if ((this._ChangeLog != value))
				{
					this.OnChangeLogChanging(value);
					this.SendPropertyChanging();
					this._ChangeLog = value;
					this.SendPropertyChanged("ChangeLog");
					this.OnChangeLogChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
