//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLXNAVWebApp.Permissions {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="data_Permissions", Namespace="http://schemas.datacontract.org/2004/07/DTO.Classes")]
    [System.SerializableAttribute()]
    public partial class data_Permissions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> AllowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Allow {
            get {
                return this.AllowField;
            }
            set {
                if ((this.AllowField.Equals(value) != true)) {
                    this.AllowField = value;
                    this.RaisePropertyChanged("Allow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Page {
            get {
                return this.PageField;
            }
            set {
                if ((object.ReferenceEquals(this.PageField, value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UID {
            get {
                return this.UIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UIDField, value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Permissions.IBSL_Permissions")]
    public interface IBSL_Permissions {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_Permissions/GetPermissionByUser", ReplyAction="http://tempuri.org/IBSL_Permissions/GetPermissionByUserResponse")]
        GLXNAVWebApp.Permissions.data_Permissions[] GetPermissionByUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_Permissions/GetPermissionByUser", ReplyAction="http://tempuri.org/IBSL_Permissions/GetPermissionByUserResponse")]
        System.Threading.Tasks.Task<GLXNAVWebApp.Permissions.data_Permissions[]> GetPermissionByUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_Permissions/CopyPermission", ReplyAction="http://tempuri.org/IBSL_Permissions/CopyPermissionResponse")]
        string CopyPermission(string userFrom, string userTo, string CompanyFrom, string CompanyTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_Permissions/CopyPermission", ReplyAction="http://tempuri.org/IBSL_Permissions/CopyPermissionResponse")]
        System.Threading.Tasks.Task<string> CopyPermissionAsync(string userFrom, string userTo, string CompanyFrom, string CompanyTo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBSL_PermissionsChannel : GLXNAVWebApp.Permissions.IBSL_Permissions, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BSL_PermissionsClient : System.ServiceModel.ClientBase<GLXNAVWebApp.Permissions.IBSL_Permissions>, GLXNAVWebApp.Permissions.IBSL_Permissions {
        
        public BSL_PermissionsClient() {
        }
        
        public BSL_PermissionsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BSL_PermissionsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BSL_PermissionsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BSL_PermissionsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GLXNAVWebApp.Permissions.data_Permissions[] GetPermissionByUser(string username) {
            return base.Channel.GetPermissionByUser(username);
        }
        
        public System.Threading.Tasks.Task<GLXNAVWebApp.Permissions.data_Permissions[]> GetPermissionByUserAsync(string username) {
            return base.Channel.GetPermissionByUserAsync(username);
        }
        
        public string CopyPermission(string userFrom, string userTo, string CompanyFrom, string CompanyTo) {
            return base.Channel.CopyPermission(userFrom, userTo, CompanyFrom, CompanyTo);
        }
        
        public System.Threading.Tasks.Task<string> CopyPermissionAsync(string userFrom, string userTo, string CompanyFrom, string CompanyTo) {
            return base.Channel.CopyPermissionAsync(userFrom, userTo, CompanyFrom, CompanyTo);
        }
    }
}
