//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLXNAVWebApp.POWaitingForApprove {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="data_POWaitingForApprove", Namespace="http://schemas.datacontract.org/2004/07/DTO.Classes")]
    [System.SerializableAttribute()]
    public partial class data_POWaitingForApprove : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> Accept_Action_MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Action_MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApprovedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ApprovedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChangeLogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConvertTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ConvertedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Direct_Unit_CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Due_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Location_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Original_QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Replenishment_SystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Unit_of_Measure_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vendor_Item_NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vendor_NoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Accept_Action_Message {
            get {
                return this.Accept_Action_MessageField;
            }
            set {
                if ((this.Accept_Action_MessageField.Equals(value) != true)) {
                    this.Accept_Action_MessageField = value;
                    this.RaisePropertyChanged("Accept_Action_Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action_Message {
            get {
                return this.Action_MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.Action_MessageField, value) != true)) {
                    this.Action_MessageField = value;
                    this.RaisePropertyChanged("Action_Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApprovedBy {
            get {
                return this.ApprovedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprovedByField, value) != true)) {
                    this.ApprovedByField = value;
                    this.RaisePropertyChanged("ApprovedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ApprovedOn {
            get {
                return this.ApprovedOnField;
            }
            set {
                if ((this.ApprovedOnField.Equals(value) != true)) {
                    this.ApprovedOnField = value;
                    this.RaisePropertyChanged("ApprovedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Batch {
            get {
                return this.BatchField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchField, value) != true)) {
                    this.BatchField = value;
                    this.RaisePropertyChanged("Batch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChangeLog {
            get {
                return this.ChangeLogField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeLogField, value) != true)) {
                    this.ChangeLogField = value;
                    this.RaisePropertyChanged("ChangeLog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConvertType {
            get {
                return this.ConvertTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ConvertTypeField, value) != true)) {
                    this.ConvertTypeField = value;
                    this.RaisePropertyChanged("ConvertType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Converted {
            get {
                return this.ConvertedField;
            }
            set {
                if ((this.ConvertedField.Equals(value) != true)) {
                    this.ConvertedField = value;
                    this.RaisePropertyChanged("Converted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Direct_Unit_Cost {
            get {
                return this.Direct_Unit_CostField;
            }
            set {
                if ((this.Direct_Unit_CostField.Equals(value) != true)) {
                    this.Direct_Unit_CostField = value;
                    this.RaisePropertyChanged("Direct_Unit_Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Due_Date {
            get {
                return this.Due_DateField;
            }
            set {
                if ((this.Due_DateField.Equals(value) != true)) {
                    this.Due_DateField = value;
                    this.RaisePropertyChanged("Due_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location_Code {
            get {
                return this.Location_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Location_CodeField, value) != true)) {
                    this.Location_CodeField = value;
                    this.RaisePropertyChanged("Location_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Original_Quantity {
            get {
                return this.Original_QuantityField;
            }
            set {
                if ((this.Original_QuantityField.Equals(value) != true)) {
                    this.Original_QuantityField = value;
                    this.RaisePropertyChanged("Original_Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Replenishment_System {
            get {
                return this.Replenishment_SystemField;
            }
            set {
                if ((object.ReferenceEquals(this.Replenishment_SystemField, value) != true)) {
                    this.Replenishment_SystemField = value;
                    this.RaisePropertyChanged("Replenishment_System");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UID {
            get {
                return this.UIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UIDField, value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit_of_Measure_Code {
            get {
                return this.Unit_of_Measure_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Unit_of_Measure_CodeField, value) != true)) {
                    this.Unit_of_Measure_CodeField = value;
                    this.RaisePropertyChanged("Unit_of_Measure_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedOn {
            get {
                return this.UpdatedOnField;
            }
            set {
                if ((this.UpdatedOnField.Equals(value) != true)) {
                    this.UpdatedOnField = value;
                    this.RaisePropertyChanged("UpdatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vendor_Item_No {
            get {
                return this.Vendor_Item_NoField;
            }
            set {
                if ((object.ReferenceEquals(this.Vendor_Item_NoField, value) != true)) {
                    this.Vendor_Item_NoField = value;
                    this.RaisePropertyChanged("Vendor_Item_No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vendor_No {
            get {
                return this.Vendor_NoField;
            }
            set {
                if ((object.ReferenceEquals(this.Vendor_NoField, value) != true)) {
                    this.Vendor_NoField = value;
                    this.RaisePropertyChanged("Vendor_No");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="POWaitingForApprove.IBSL_POWaitingForApprove")]
    public interface IBSL_POWaitingForApprove {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_POWaitingForApprove/GetAll", ReplyAction="http://tempuri.org/IBSL_POWaitingForApprove/GetAllResponse")]
        GLXNAVWebApp.POWaitingForApprove.data_POWaitingForApprove[] GetAll(string batch, System.DateTime fromdate, System.DateTime todate, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_POWaitingForApprove/GetAll", ReplyAction="http://tempuri.org/IBSL_POWaitingForApprove/GetAllResponse")]
        System.Threading.Tasks.Task<GLXNAVWebApp.POWaitingForApprove.data_POWaitingForApprove[]> GetAllAsync(string batch, System.DateTime fromdate, System.DateTime todate, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_POWaitingForApprove/CheckPermission", ReplyAction="http://tempuri.org/IBSL_POWaitingForApprove/CheckPermissionResponse")]
        bool CheckPermission(string company, string username, string page, string action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_POWaitingForApprove/CheckPermission", ReplyAction="http://tempuri.org/IBSL_POWaitingForApprove/CheckPermissionResponse")]
        System.Threading.Tasks.Task<bool> CheckPermissionAsync(string company, string username, string page, string action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_POWaitingForApprove/UpdateToApprove", ReplyAction="http://tempuri.org/IBSL_POWaitingForApprove/UpdateToApproveResponse")]
        string UpdateToApprove(string uid, string username, string newStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_POWaitingForApprove/UpdateToApprove", ReplyAction="http://tempuri.org/IBSL_POWaitingForApprove/UpdateToApproveResponse")]
        System.Threading.Tasks.Task<string> UpdateToApproveAsync(string uid, string username, string newStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_POWaitingForApprove/Reopen", ReplyAction="http://tempuri.org/IBSL_POWaitingForApprove/ReopenResponse")]
        string Reopen(string uid, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_POWaitingForApprove/Reopen", ReplyAction="http://tempuri.org/IBSL_POWaitingForApprove/ReopenResponse")]
        System.Threading.Tasks.Task<string> ReopenAsync(string uid, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_POWaitingForApprove/UpdateConverted", ReplyAction="http://tempuri.org/IBSL_POWaitingForApprove/UpdateConvertedResponse")]
        string UpdateConverted(string uid, string convertType, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_POWaitingForApprove/UpdateConverted", ReplyAction="http://tempuri.org/IBSL_POWaitingForApprove/UpdateConvertedResponse")]
        System.Threading.Tasks.Task<string> UpdateConvertedAsync(string uid, string convertType, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_POWaitingForApprove/InsertComment", ReplyAction="http://tempuri.org/IBSL_POWaitingForApprove/InsertCommentResponse")]
        string InsertComment(string uid, string commentText, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_POWaitingForApprove/InsertComment", ReplyAction="http://tempuri.org/IBSL_POWaitingForApprove/InsertCommentResponse")]
        System.Threading.Tasks.Task<string> InsertCommentAsync(string uid, string commentText, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_POWaitingForApprove/TobeDeleted", ReplyAction="http://tempuri.org/IBSL_POWaitingForApprove/TobeDeletedResponse")]
        string TobeDeleted(string uid, string username, string newStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_POWaitingForApprove/TobeDeleted", ReplyAction="http://tempuri.org/IBSL_POWaitingForApprove/TobeDeletedResponse")]
        System.Threading.Tasks.Task<string> TobeDeletedAsync(string uid, string username, string newStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_POWaitingForApprove/GetRecIdFromKey", ReplyAction="http://tempuri.org/IBSL_POWaitingForApprove/GetRecIdFromKeyResponse")]
        GLXNAVWebApp.POWaitingForApprove.data_POWaitingForApprove GetRecIdFromKey(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_POWaitingForApprove/GetRecIdFromKey", ReplyAction="http://tempuri.org/IBSL_POWaitingForApprove/GetRecIdFromKeyResponse")]
        System.Threading.Tasks.Task<GLXNAVWebApp.POWaitingForApprove.data_POWaitingForApprove> GetRecIdFromKeyAsync(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_POWaitingForApprove/UpdateData", ReplyAction="http://tempuri.org/IBSL_POWaitingForApprove/UpdateDataResponse")]
        string UpdateData(string uid, GLXNAVWebApp.POWaitingForApprove.data_POWaitingForApprove data, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_POWaitingForApprove/UpdateData", ReplyAction="http://tempuri.org/IBSL_POWaitingForApprove/UpdateDataResponse")]
        System.Threading.Tasks.Task<string> UpdateDataAsync(string uid, GLXNAVWebApp.POWaitingForApprove.data_POWaitingForApprove data, string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBSL_POWaitingForApproveChannel : GLXNAVWebApp.POWaitingForApprove.IBSL_POWaitingForApprove, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BSL_POWaitingForApproveClient : System.ServiceModel.ClientBase<GLXNAVWebApp.POWaitingForApprove.IBSL_POWaitingForApprove>, GLXNAVWebApp.POWaitingForApprove.IBSL_POWaitingForApprove {
        
        public BSL_POWaitingForApproveClient() {
        }
        
        public BSL_POWaitingForApproveClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BSL_POWaitingForApproveClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BSL_POWaitingForApproveClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BSL_POWaitingForApproveClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GLXNAVWebApp.POWaitingForApprove.data_POWaitingForApprove[] GetAll(string batch, System.DateTime fromdate, System.DateTime todate, string username) {
            return base.Channel.GetAll(batch, fromdate, todate, username);
        }
        
        public System.Threading.Tasks.Task<GLXNAVWebApp.POWaitingForApprove.data_POWaitingForApprove[]> GetAllAsync(string batch, System.DateTime fromdate, System.DateTime todate, string username) {
            return base.Channel.GetAllAsync(batch, fromdate, todate, username);
        }
        
        public bool CheckPermission(string company, string username, string page, string action) {
            return base.Channel.CheckPermission(company, username, page, action);
        }
        
        public System.Threading.Tasks.Task<bool> CheckPermissionAsync(string company, string username, string page, string action) {
            return base.Channel.CheckPermissionAsync(company, username, page, action);
        }
        
        public string UpdateToApprove(string uid, string username, string newStatus) {
            return base.Channel.UpdateToApprove(uid, username, newStatus);
        }
        
        public System.Threading.Tasks.Task<string> UpdateToApproveAsync(string uid, string username, string newStatus) {
            return base.Channel.UpdateToApproveAsync(uid, username, newStatus);
        }
        
        public string Reopen(string uid, string username) {
            return base.Channel.Reopen(uid, username);
        }
        
        public System.Threading.Tasks.Task<string> ReopenAsync(string uid, string username) {
            return base.Channel.ReopenAsync(uid, username);
        }
        
        public string UpdateConverted(string uid, string convertType, string username) {
            return base.Channel.UpdateConverted(uid, convertType, username);
        }
        
        public System.Threading.Tasks.Task<string> UpdateConvertedAsync(string uid, string convertType, string username) {
            return base.Channel.UpdateConvertedAsync(uid, convertType, username);
        }
        
        public string InsertComment(string uid, string commentText, string username) {
            return base.Channel.InsertComment(uid, commentText, username);
        }
        
        public System.Threading.Tasks.Task<string> InsertCommentAsync(string uid, string commentText, string username) {
            return base.Channel.InsertCommentAsync(uid, commentText, username);
        }
        
        public string TobeDeleted(string uid, string username, string newStatus) {
            return base.Channel.TobeDeleted(uid, username, newStatus);
        }
        
        public System.Threading.Tasks.Task<string> TobeDeletedAsync(string uid, string username, string newStatus) {
            return base.Channel.TobeDeletedAsync(uid, username, newStatus);
        }
        
        public GLXNAVWebApp.POWaitingForApprove.data_POWaitingForApprove GetRecIdFromKey(string uid) {
            return base.Channel.GetRecIdFromKey(uid);
        }
        
        public System.Threading.Tasks.Task<GLXNAVWebApp.POWaitingForApprove.data_POWaitingForApprove> GetRecIdFromKeyAsync(string uid) {
            return base.Channel.GetRecIdFromKeyAsync(uid);
        }
        
        public string UpdateData(string uid, GLXNAVWebApp.POWaitingForApprove.data_POWaitingForApprove data, string username) {
            return base.Channel.UpdateData(uid, data, username);
        }
        
        public System.Threading.Tasks.Task<string> UpdateDataAsync(string uid, GLXNAVWebApp.POWaitingForApprove.data_POWaitingForApprove data, string username) {
            return base.Channel.UpdateDataAsync(uid, data, username);
        }
    }
}
