//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GLXNAVWebApp.PurchaseOrder_CU {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PurchaseOrder_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/PurchaseOrder")]
    public partial class PurchaseOrder : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UseOneJnlOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitializeRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetHideDialogOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestConnectionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PurchaseOrder() {
            this.Url = global::GLXNAVWebApp.Properties.Settings.Default.GLXNAVWebApp_PurchaseOrder_CU_PurchaseOrder;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UseOneJnlCompletedEventHandler UseOneJnlCompleted;
        
        /// <remarks/>
        public event InitializeRequestCompletedEventHandler InitializeRequestCompleted;
        
        /// <remarks/>
        public event SetHideDialogCompletedEventHandler SetHideDialogCompleted;
        
        /// <remarks/>
        public event TestConnectionCompletedEventHandler TestConnectionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PurchaseOrder:UseOneJnl", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PurchaseOrder", ResponseElementName="UseOneJnl_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PurchaseOrder", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UseOneJnl() {
            this.Invoke("UseOneJnl", new object[0]);
        }
        
        /// <remarks/>
        public void UseOneJnlAsync() {
            this.UseOneJnlAsync(null);
        }
        
        /// <remarks/>
        public void UseOneJnlAsync(object userState) {
            if ((this.UseOneJnlOperationCompleted == null)) {
                this.UseOneJnlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUseOneJnlOperationCompleted);
            }
            this.InvokeAsync("UseOneJnl", new object[0], this.UseOneJnlOperationCompleted, userState);
        }
        
        private void OnUseOneJnlOperationCompleted(object arg) {
            if ((this.UseOneJnlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UseOneJnlCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PurchaseOrder:InitializeRequest", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PurchaseOrder", ResponseElementName="InitializeRequest_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PurchaseOrder", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InitializeRequest([System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime expirationDate, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime orderDate, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime postingDate, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime expectedReceiptDate, string yourRef) {
            this.Invoke("InitializeRequest", new object[] {
                        expirationDate,
                        orderDate,
                        postingDate,
                        expectedReceiptDate,
                        yourRef});
        }
        
        /// <remarks/>
        public void InitializeRequestAsync(System.DateTime expirationDate, System.DateTime orderDate, System.DateTime postingDate, System.DateTime expectedReceiptDate, string yourRef) {
            this.InitializeRequestAsync(expirationDate, orderDate, postingDate, expectedReceiptDate, yourRef, null);
        }
        
        /// <remarks/>
        public void InitializeRequestAsync(System.DateTime expirationDate, System.DateTime orderDate, System.DateTime postingDate, System.DateTime expectedReceiptDate, string yourRef, object userState) {
            if ((this.InitializeRequestOperationCompleted == null)) {
                this.InitializeRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializeRequestOperationCompleted);
            }
            this.InvokeAsync("InitializeRequest", new object[] {
                        expirationDate,
                        orderDate,
                        postingDate,
                        expectedReceiptDate,
                        yourRef}, this.InitializeRequestOperationCompleted, userState);
        }
        
        private void OnInitializeRequestOperationCompleted(object arg) {
            if ((this.InitializeRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitializeRequestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PurchaseOrder:SetHideDialog", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PurchaseOrder", ResponseElementName="SetHideDialog_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PurchaseOrder", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetHideDialog(bool newHideDialog) {
            this.Invoke("SetHideDialog", new object[] {
                        newHideDialog});
        }
        
        /// <remarks/>
        public void SetHideDialogAsync(bool newHideDialog) {
            this.SetHideDialogAsync(newHideDialog, null);
        }
        
        /// <remarks/>
        public void SetHideDialogAsync(bool newHideDialog, object userState) {
            if ((this.SetHideDialogOperationCompleted == null)) {
                this.SetHideDialogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetHideDialogOperationCompleted);
            }
            this.InvokeAsync("SetHideDialog", new object[] {
                        newHideDialog}, this.SetHideDialogOperationCompleted, userState);
        }
        
        private void OnSetHideDialogOperationCompleted(object arg) {
            if ((this.SetHideDialogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetHideDialogCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PurchaseOrder:TestConnection", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PurchaseOrder", ResponseElementName="TestConnection_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PurchaseOrder", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string TestConnection() {
            object[] results = this.Invoke("TestConnection", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestConnectionAsync() {
            this.TestConnectionAsync(null);
        }
        
        /// <remarks/>
        public void TestConnectionAsync(object userState) {
            if ((this.TestConnectionOperationCompleted == null)) {
                this.TestConnectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestConnectionOperationCompleted);
            }
            this.InvokeAsync("TestConnection", new object[0], this.TestConnectionOperationCompleted, userState);
        }
        
        private void OnTestConnectionOperationCompleted(object arg) {
            if ((this.TestConnectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestConnectionCompleted(this, new TestConnectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UseOneJnlCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void InitializeRequestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SetHideDialogCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void TestConnectionCompletedEventHandler(object sender, TestConnectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestConnectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestConnectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591