//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLXNAVWebApp.GLXRequisitionWkshName {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="data_RequisitionWkshName", Namespace="http://schemas.datacontract.org/2004/07/DTO.Classes")]
    [System.SerializableAttribute()]
    public partial class data_RequisitionWkshName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> RecurringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Template_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Worksheet_Template_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Recurring {
            get {
                return this.RecurringField;
            }
            set {
                if ((this.RecurringField.Equals(value) != true)) {
                    this.RecurringField = value;
                    this.RaisePropertyChanged("Recurring");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Template_Type {
            get {
                return this.Template_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Template_TypeField, value) != true)) {
                    this.Template_TypeField = value;
                    this.RaisePropertyChanged("Template_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UID {
            get {
                return this.UIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UIDField, value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Worksheet_Template_Name {
            get {
                return this.Worksheet_Template_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Worksheet_Template_NameField, value) != true)) {
                    this.Worksheet_Template_NameField = value;
                    this.RaisePropertyChanged("Worksheet_Template_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GLXRequisitionWkshName.IBSL_RequisitionWkshName")]
    public interface IBSL_RequisitionWkshName {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_RequisitionWkshName/GetAll", ReplyAction="http://tempuri.org/IBSL_RequisitionWkshName/GetAllResponse")]
        GLXNAVWebApp.GLXRequisitionWkshName.data_RequisitionWkshName[] GetAll(string company, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_RequisitionWkshName/GetAll", ReplyAction="http://tempuri.org/IBSL_RequisitionWkshName/GetAllResponse")]
        System.Threading.Tasks.Task<GLXNAVWebApp.GLXRequisitionWkshName.data_RequisitionWkshName[]> GetAllAsync(string company, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_RequisitionWkshName/GetDataByUser", ReplyAction="http://tempuri.org/IBSL_RequisitionWkshName/GetDataByUserResponse")]
        GLXNAVWebApp.GLXRequisitionWkshName.data_RequisitionWkshName[] GetDataByUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_RequisitionWkshName/GetDataByUser", ReplyAction="http://tempuri.org/IBSL_RequisitionWkshName/GetDataByUserResponse")]
        System.Threading.Tasks.Task<GLXNAVWebApp.GLXRequisitionWkshName.data_RequisitionWkshName[]> GetDataByUserAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBSL_RequisitionWkshNameChannel : GLXNAVWebApp.GLXRequisitionWkshName.IBSL_RequisitionWkshName, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BSL_RequisitionWkshNameClient : System.ServiceModel.ClientBase<GLXNAVWebApp.GLXRequisitionWkshName.IBSL_RequisitionWkshName>, GLXNAVWebApp.GLXRequisitionWkshName.IBSL_RequisitionWkshName {
        
        public BSL_RequisitionWkshNameClient() {
        }
        
        public BSL_RequisitionWkshNameClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BSL_RequisitionWkshNameClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BSL_RequisitionWkshNameClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BSL_RequisitionWkshNameClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GLXNAVWebApp.GLXRequisitionWkshName.data_RequisitionWkshName[] GetAll(string company, string username) {
            return base.Channel.GetAll(company, username);
        }
        
        public System.Threading.Tasks.Task<GLXNAVWebApp.GLXRequisitionWkshName.data_RequisitionWkshName[]> GetAllAsync(string company, string username) {
            return base.Channel.GetAllAsync(company, username);
        }
        
        public GLXNAVWebApp.GLXRequisitionWkshName.data_RequisitionWkshName[] GetDataByUser(string username) {
            return base.Channel.GetDataByUser(username);
        }
        
        public System.Threading.Tasks.Task<GLXNAVWebApp.GLXRequisitionWkshName.data_RequisitionWkshName[]> GetDataByUserAsync(string username) {
            return base.Channel.GetDataByUserAsync(username);
        }
    }
}
