//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLXNAVWebApp.RBSL_LocationAndAccount {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="data_LocationAndAccount", Namespace="http://schemas.datacontract.org/2004/07/DTO.Classes")]
    [System.SerializableAttribute()]
    public partial class data_LocationAndAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UID {
            get {
                return this.UIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UIDField, value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RBSL_LocationAndAccount.IBSL_LocationAndAccount")]
    public interface IBSL_LocationAndAccount {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_LocationAndAccount/GetLocationByUser", ReplyAction="http://tempuri.org/IBSL_LocationAndAccount/GetLocationByUserResponse")]
        GLXNAVWebApp.RBSL_LocationAndAccount.data_LocationAndAccount[] GetLocationByUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_LocationAndAccount/GetLocationByUser", ReplyAction="http://tempuri.org/IBSL_LocationAndAccount/GetLocationByUserResponse")]
        System.Threading.Tasks.Task<GLXNAVWebApp.RBSL_LocationAndAccount.data_LocationAndAccount[]> GetLocationByUserAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBSL_LocationAndAccountChannel : GLXNAVWebApp.RBSL_LocationAndAccount.IBSL_LocationAndAccount, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BSL_LocationAndAccountClient : System.ServiceModel.ClientBase<GLXNAVWebApp.RBSL_LocationAndAccount.IBSL_LocationAndAccount>, GLXNAVWebApp.RBSL_LocationAndAccount.IBSL_LocationAndAccount {
        
        public BSL_LocationAndAccountClient() {
        }
        
        public BSL_LocationAndAccountClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BSL_LocationAndAccountClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BSL_LocationAndAccountClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BSL_LocationAndAccountClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GLXNAVWebApp.RBSL_LocationAndAccount.data_LocationAndAccount[] GetLocationByUser(string username) {
            return base.Channel.GetLocationByUser(username);
        }
        
        public System.Threading.Tasks.Task<GLXNAVWebApp.RBSL_LocationAndAccount.data_LocationAndAccount[]> GetLocationByUserAsync(string username) {
            return base.Channel.GetLocationByUserAsync(username);
        }
    }
}
