//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLXNAVWebApp.GLXAccountSVC {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="data_GLXAccount", Namespace="http://schemas.datacontract.org/2004/07/DTO.Classes")]
    [System.SerializableAttribute()]
    public partial class data_GLXAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UID {
            get {
                return this.UIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UIDField, value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="data_Account", Namespace="http://schemas.datacontract.org/2004/07/DTO.Classes")]
    [System.SerializableAttribute()]
    public partial class data_Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fullname {
            get {
                return this.FullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullnameField, value) != true)) {
                    this.FullnameField = value;
                    this.RaisePropertyChanged("Fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UID {
            get {
                return this.UIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UIDField, value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="data_UserCreateRequest", Namespace="http://schemas.datacontract.org/2004/07/DTO.Classes")]
    [System.SerializableAttribute()]
    public partial class data_UserCreateRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompaniesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Batch {
            get {
                return this.BatchField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchField, value) != true)) {
                    this.BatchField = value;
                    this.RaisePropertyChanged("Batch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Companies {
            get {
                return this.CompaniesField;
            }
            set {
                if ((object.ReferenceEquals(this.CompaniesField, value) != true)) {
                    this.CompaniesField = value;
                    this.RaisePropertyChanged("Companies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GLXAccountSVC.IBSL_GLXAccount")]
    public interface IBSL_GLXAccount {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_GLXAccount/CheckExistsItem", ReplyAction="http://tempuri.org/IBSL_GLXAccount/CheckExistsItemResponse")]
        bool CheckExistsItem(string username, string company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_GLXAccount/CheckExistsItem", ReplyAction="http://tempuri.org/IBSL_GLXAccount/CheckExistsItemResponse")]
        System.Threading.Tasks.Task<bool> CheckExistsItemAsync(string username, string company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_GLXAccount/GetAll", ReplyAction="http://tempuri.org/IBSL_GLXAccount/GetAllResponse")]
        GLXNAVWebApp.GLXAccountSVC.data_GLXAccount[] GetAll(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_GLXAccount/GetAll", ReplyAction="http://tempuri.org/IBSL_GLXAccount/GetAllResponse")]
        System.Threading.Tasks.Task<GLXNAVWebApp.GLXAccountSVC.data_GLXAccount[]> GetAllAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_GLXAccount/GetAllAccount", ReplyAction="http://tempuri.org/IBSL_GLXAccount/GetAllAccountResponse")]
        GLXNAVWebApp.GLXAccountSVC.data_Account[] GetAllAccount(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_GLXAccount/GetAllAccount", ReplyAction="http://tempuri.org/IBSL_GLXAccount/GetAllAccountResponse")]
        System.Threading.Tasks.Task<GLXNAVWebApp.GLXAccountSVC.data_Account[]> GetAllAccountAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_GLXAccount/createUser", ReplyAction="http://tempuri.org/IBSL_GLXAccount/createUserResponse")]
        string createUser(GLXNAVWebApp.GLXAccountSVC.data_UserCreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_GLXAccount/createUser", ReplyAction="http://tempuri.org/IBSL_GLXAccount/createUserResponse")]
        System.Threading.Tasks.Task<string> createUserAsync(GLXNAVWebApp.GLXAccountSVC.data_UserCreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_GLXAccount/DelUser", ReplyAction="http://tempuri.org/IBSL_GLXAccount/DelUserResponse")]
        string DelUser(string uname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSL_GLXAccount/DelUser", ReplyAction="http://tempuri.org/IBSL_GLXAccount/DelUserResponse")]
        System.Threading.Tasks.Task<string> DelUserAsync(string uname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBSL_GLXAccountChannel : GLXNAVWebApp.GLXAccountSVC.IBSL_GLXAccount, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BSL_GLXAccountClient : System.ServiceModel.ClientBase<GLXNAVWebApp.GLXAccountSVC.IBSL_GLXAccount>, GLXNAVWebApp.GLXAccountSVC.IBSL_GLXAccount {
        
        public BSL_GLXAccountClient() {
        }
        
        public BSL_GLXAccountClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BSL_GLXAccountClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BSL_GLXAccountClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BSL_GLXAccountClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckExistsItem(string username, string company) {
            return base.Channel.CheckExistsItem(username, company);
        }
        
        public System.Threading.Tasks.Task<bool> CheckExistsItemAsync(string username, string company) {
            return base.Channel.CheckExistsItemAsync(username, company);
        }
        
        public GLXNAVWebApp.GLXAccountSVC.data_GLXAccount[] GetAll(string username) {
            return base.Channel.GetAll(username);
        }
        
        public System.Threading.Tasks.Task<GLXNAVWebApp.GLXAccountSVC.data_GLXAccount[]> GetAllAsync(string username) {
            return base.Channel.GetAllAsync(username);
        }
        
        public GLXNAVWebApp.GLXAccountSVC.data_Account[] GetAllAccount(string username) {
            return base.Channel.GetAllAccount(username);
        }
        
        public System.Threading.Tasks.Task<GLXNAVWebApp.GLXAccountSVC.data_Account[]> GetAllAccountAsync(string username) {
            return base.Channel.GetAllAccountAsync(username);
        }
        
        public string createUser(GLXNAVWebApp.GLXAccountSVC.data_UserCreateRequest request) {
            return base.Channel.createUser(request);
        }
        
        public System.Threading.Tasks.Task<string> createUserAsync(GLXNAVWebApp.GLXAccountSVC.data_UserCreateRequest request) {
            return base.Channel.createUserAsync(request);
        }
        
        public string DelUser(string uname) {
            return base.Channel.DelUser(uname);
        }
        
        public System.Threading.Tasks.Task<string> DelUserAsync(string uname) {
            return base.Channel.DelUserAsync(uname);
        }
    }
}
